name: Continous integration
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
          python-version: '3.7'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        nosetests tests
